CREATE TABLE IF NOT EXISTS submissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  name text NOT NULL,
  email text NOT NULL,
  phone text,
  location text,
  experience text,
  preferred_contact text,
  goals text,
  message text,
  source text NOT NULL DEFAULT 'website',
  ip text,
  user_agent text
);

CREATE INDEX IF NOT EXISTS submissions_created_at_idx
  ON submissions (created_at DESC);
