CREATE TABLE IF NOT EXISTS services (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text,
  duration_minutes integer,
  price_cents integer,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text
);

CREATE TABLE IF NOT EXISTS clients (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL,
  phone text,
  location text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text
);

CREATE INDEX IF NOT EXISTS clients_email_idx ON clients (email);

CREATE TABLE IF NOT EXISTS sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id bigint NOT NULL REFERENCES clients (id),
  service_id bigint REFERENCES services (id),
  starts_at timestamptz NOT NULL,
  ends_at timestamptz NOT NULL,
  status text NOT NULL DEFAULT 'scheduled',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text,
  CONSTRAINT sessions_status_check CHECK (status IN ('scheduled', 'completed', 'cancelled'))
);

CREATE INDEX IF NOT EXISTS sessions_client_id_idx ON sessions (client_id);

CREATE INDEX IF NOT EXISTS sessions_service_id_idx ON sessions (service_id);

CREATE INDEX IF NOT EXISTS sessions_starts_at_idx ON sessions (starts_at);

ALTER TABLE submissions
  ADD COLUMN IF NOT EXISTS client_id bigint REFERENCES clients (id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS submissions_client_id_idx ON submissions (client_id);
