ALTER TABLE sessions
  ADD COLUMN IF NOT EXISTS manage_token text;

ALTER TABLE sessions
  ADD COLUMN IF NOT EXISTS reminder_24h_sent_at timestamptz;

ALTER TABLE sessions
  ADD COLUMN IF NOT EXISTS reminder_1h_sent_at timestamptz;

CREATE UNIQUE INDEX IF NOT EXISTS sessions_manage_token_idx ON sessions (manage_token);

UPDATE sessions
SET manage_token = gen_random_uuid()::text
WHERE manage_token IS NULL;

CREATE TABLE IF NOT EXISTS payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id bigint REFERENCES clients (id) ON DELETE SET NULL,
  session_id bigint REFERENCES sessions (id) ON DELETE SET NULL,
  stripe_event_id text NOT NULL UNIQUE,
  stripe_object_id text,
  amount_cents integer,
  currency text,
  status text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text
);
