CREATE TABLE IF NOT EXISTS availability_rules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  weekday smallint NOT NULL,
  start_minute integer NOT NULL,
  end_minute integer NOT NULL,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT availability_rules_weekday_check CHECK (weekday BETWEEN 0 AND 6),
  CONSTRAINT availability_rules_minutes_check CHECK (start_minute >= 0 AND end_minute <= 1440 AND end_minute > start_minute),
  CONSTRAINT availability_rules_weekday_unique UNIQUE (weekday)
);

INSERT INTO availability_rules (weekday, start_minute, end_minute)
SELECT CAST(trim(w) AS smallint), a.work_start_minute, a.work_end_minute
FROM availability a CROSS JOIN unnest(string_to_array(a.weekdays, ',')) AS w
WHERE a.id = 1 AND NOT EXISTS (SELECT 1 FROM availability_rules);

CREATE TABLE IF NOT EXISTS availability_blocks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  starts_at timestamptz NOT NULL,
  ends_at timestamptz NOT NULL,
  reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by text,
  CONSTRAINT availability_blocks_range_check CHECK (ends_at > starts_at)
);

CREATE INDEX IF NOT EXISTS availability_blocks_starts_at_idx ON availability_blocks (starts_at);

ALTER TABLE availability ADD COLUMN IF NOT EXISTS horizon_days integer NOT NULL DEFAULT 28;

ALTER TABLE sessions DROP CONSTRAINT IF EXISTS sessions_status_check;

UPDATE sessions SET status = 'pending' WHERE status = 'requested';

UPDATE sessions SET status = 'approved' WHERE status = 'accepted';

UPDATE sessions SET status = 'declined' WHERE status = 'denied';

ALTER TABLE sessions
  ADD CONSTRAINT sessions_status_check
  CHECK (status IN ('pending', 'approved', 'scheduled', 'completed', 'cancelled', 'declined'));

ALTER TABLE sessions ADD COLUMN IF NOT EXISTS decided_at timestamptz;

ALTER TABLE sessions ADD COLUMN IF NOT EXISTS calendar_provider text;

ALTER TABLE sessions RENAME COLUMN google_event_id TO external_event_id;

ALTER TABLE sessions ALTER COLUMN calendar_sync_status SET DEFAULT 'none';

UPDATE sessions SET calendar_sync_status = 'none' WHERE calendar_sync_status = 'pending';

ALTER TABLE sessions
  ADD CONSTRAINT sessions_no_overlap
  EXCLUDE USING gist (tstzrange(starts_at, ends_at, '[)') WITH &&)
  WHERE (status IN ('pending', 'approved', 'scheduled'));
